###`Q-1:` Find the nearest element in the array to a given integer.
```
Ex:-
a=23 and array - [10 17 24 31 38 45 52 59].
Nearest element is 24
```
Hint: Read about this function `argmin()`

In [2]:
import numpy as np
from scipy import stats


In [3]:
# code here
arr=np.array([10,17,24,31,38,45,52,59])
a=23
print("The Nearest Element is",arr[np.abs(arr-a).argmin()])

The Nearest Element is 24


###`Q-2:` Replace multiples of 3 or 5 as 0 in the given array.
```
arr=[1 2 3 4 5 6 7 9]

result-> [1 2 0 4 0 0 7 0]
```

In [4]:
# code here
arr=np.array([1,2,3,4,5,6,7,9])
arr[(arr%3==0) | (arr%5==0)]=0
print("result->",arr)

result-> [1 2 0 4 0 0 7 0]


###`Q-3:` Use Fancy Indexing.
1. Double the array elements at  given indexes
```
arr = np.arrange(10)
indexes = [0,3,4,9]
```
Result -> `[ 0  1  2  6  8  5  6  7  8 18]`

2. Using a given array make a different array as in below example
```
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
```
* Internal-repetion should be as length of the array.

Hint:
```
if a is an array
a = [2,4]
a[[1,1,0,1]] will result in-> [4 4 2 4]
```

In [23]:
# code here
arr = np.arange(10)
print(arr)
indexes = [0,3,4,9]
arr[indexes]=arr[indexes]*2
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  6  8  5  6  7  8 18]


###`Q-4:` Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.
```
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

```

In [69]:
# code here
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])
valid_values=arr[~np.isnan(arr)]
frequent_val=stats.mode(valid_values)[0]
arr[np.isnan(arr)]=frequent_val
print(arr)

[[1. 2. 2.]
 [4. 2. 6.]
 [2. 2. 5.]]


### `Q-5:` Write a NumPy program

- to find the missing data in a given array. Return a boolean matrix.
- also try to fill those missing values with 0. For that, you can use `np.nan_to_num(a)`

```python
import numpy as np

np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
```

In [76]:
# code here
ar=np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
ar[np.isnan(ar)]=0
print(ar)

[[ 3.  2.  0.  1.]
 [10. 12. 10.  9.]
 [ 5.  0.  1.  0.]]


###`Q-6:` Given two arrays, X and Y, construct the Cauchy matrix C.
`Cij =1/(xi - yj)`

http://en.wikipedia.org/wiki/Cauchy_matrix
```
x = numpy.array([1,2,3,4]).reshape((-1, 1)
y = numpy.array([5,6,7])
```

In [83]:
# code here
x = np.array([1,2,3,4]).reshape((-1, 1))
y = np.array([5,6,7])
cauchy_mat=1/(x-y)
print(cauchy_mat)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


###`Q-7:` Plot this below equation.

$$\large y = \frac{e^x - e^{-x}}{e^x + e^{-x}}$$

**Note: This equation is called tanh activation function. In deep learning, many times this function is used. If you find some difference between the sigmoid function and this tanh function, note that to your notebook.**

In [84]:
# code here
arraye=np.array([3,4,5,6,7,8])
y=(np.exp(arraye)-np.exp(-arraye))/((np.exp(arraye))+np.exp(-arraye))
print(y)

[0.99505475 0.9993293  0.9999092  0.99998771 0.99999834 0.99999977]


### `Q-8:` Plot the below equation.

$$\large y = \sqrt{36 - (x - 4)^2} + 2$$

The range of x should be between -2 to 10. $x ∈ [-2, 10]$



In [90]:
# code here
x=np.arange(16).reshape(4,4)
x=np.clip(x,-2,10)
y=np.sqrt(36-(x-4)**2)+2
print(y)

[[6.47213595 7.19615242 7.65685425 7.91607978]
 [8.         7.91607978 7.65685425 7.19615242]
 [6.47213595 5.31662479 2.         2.        ]
 [2.         2.         2.         2.        ]]


### `Q-9:` Write a program implement Boradcasting Rule to check if two array can be added or not.
Given tuples of shapes.
```
shape of a- (3,2,2)
shape of b- (2,2)

check_broadcast(a, b) -> return Boolean (True if can broadcasted, False other wise.)
```

In [3]:
# code here
a=np.array([3,2,2])[::-1]
b=np.array([2,2])[::-1]
def check_boradcast(a,b):
    for x,y in zip(a,b):
        if x!=y and x!=1 and y!=1:
            return False
        return True
check_boradcast(a,b)


True