In [4]:
#Code here
vector=np.linspace(0,1,12)[1:-1]
vector

NameError: name 'np' is not defined

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
ide_mat=np.identity(3)
ide_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
mat_of_5=np.linspace(0,4,27)[1:-1].reshape(5,5)
mat_of_5

array([[0.15384615, 0.30769231, 0.46153846, 0.61538462, 0.76923077],
       [0.92307692, 1.07692308, 1.23076923, 1.38461538, 1.53846154],
       [1.69230769, 1.84615385, 2.        , 2.15384615, 2.30769231],
       [2.46153846, 2.61538462, 2.76923077, 2.92307692, 3.07692308],
       [3.23076923, 3.38461538, 3.53846154, 3.69230769, 3.84615385]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
coordinates=np.random.randint(1,100,(10,2))
point=np.array([2,3])
print(coordinates)
np.sqrt(np.sum((point-coordinates)**2,axis=1))


[[31  2]
 [49 45]
 [33 24]
 [96 49]
 [ 2  5]
 [65 39]
 [74 58]
 [15 36]
 [12 23]
 [60 93]]


array([ 29.01723626,  63.03173804,  37.44329045, 104.65180362,
         2.        ,  72.56031973,  90.60353194,  35.4682957 ,
        22.36067977, 107.07007051])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
index=np.unravel_index(99,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
inp=input("Enter a space separated list of numbers ").strip().split()
rever=np.array(inp[::-1],dtype=np.float32)
print(rever)

[8. 7. 6. 5. 4. 3. 2.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
arr=np.array([3,4,5,6,7,8,9,10,11])
np.size(arr)

9

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

def softmax(arr):
    z=np.sum(np.exp(arr))
    sft=np.exp(arr)/z
    return sft
softmax(np.array([86.03331084, 37.7285648  ,48.64908087 ,87.16563062 ,38.40852563 ,37.20006318]))


array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [62]:
#Coder here
def infinite_array(*args):
    for i in args:
        if type(i)!=np.ndarray:
            raise TypeError("There should be Numpy Array")
        elif type(i)!=np.ndim:
            raise TypeError("There should be one D array")
        else:
            result_arr=np.hstack(i)
    return result_arr
infinite_array(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

TypeError: There should be one D array

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
arr=np.linspace(10,100,100).reshape(25,4)
print(arr)
arr=np.flip(arr).reshape(1,-1)
print(arr-np.mean(arr,axis=1))

[[ 10.          10.90909091  11.81818182  12.72727273]
 [ 13.63636364  14.54545455  15.45454545  16.36363636]
 [ 17.27272727  18.18181818  19.09090909  20.        ]
 [ 20.90909091  21.81818182  22.72727273  23.63636364]
 [ 24.54545455  25.45454545  26.36363636  27.27272727]
 [ 28.18181818  29.09090909  30.          30.90909091]
 [ 31.81818182  32.72727273  33.63636364  34.54545455]
 [ 35.45454545  36.36363636  37.27272727  38.18181818]
 [ 39.09090909  40.          40.90909091  41.81818182]
 [ 42.72727273  43.63636364  44.54545455  45.45454545]
 [ 46.36363636  47.27272727  48.18181818  49.09090909]
 [ 50.          50.90909091  51.81818182  52.72727273]
 [ 53.63636364  54.54545455  55.45454545  56.36363636]
 [ 57.27272727  58.18181818  59.09090909  60.        ]
 [ 60.90909091  61.81818182  62.72727273  63.63636364]
 [ 64.54545455  65.45454545  66.36363636  67.27272727]
 [ 68.18181818  69.09090909  70.          70.90909091]
 [ 71.81818182  72.72727273  73.63636364  74.54545455]
 [ 75.4545

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [10]:
#Code here
arr=np.random.randint(10,100,(25,4))
print(arr)
arr[:,[1,0,2,3]]
print(arr)

[[89 95 47 34]
 [44 54 43 97]
 [35 30 90 79]
 [16 52 82 10]
 [39 47 85 92]
 [57 13 74 26]
 [24 22 24 72]
 [83 37 65 61]
 [81 24 27 63]
 [95 17 52 84]
 [58 47 58 30]
 [66 52 86 90]
 [33 63 34 45]
 [25 70 34 57]
 [81 37 63 18]
 [35 65 75 96]
 [71 15 66 90]
 [71 85 20 65]
 [59 90 18 84]
 [74 28 32 60]
 [71 24 88 22]
 [82 42 92 97]
 [62 11 29 10]
 [13 52 89 18]
 [61 41 71 47]]
[[89 95 47 34]
 [44 54 43 97]
 [35 30 90 79]
 [16 52 82 10]
 [39 47 85 92]
 [57 13 74 26]
 [24 22 24 72]
 [83 37 65 61]
 [81 24 27 63]
 [95 17 52 84]
 [58 47 58 30]
 [66 52 86 90]
 [33 63 34 45]
 [25 70 34 57]
 [81 37 63 18]
 [35 65 75 96]
 [71 15 66 90]
 [71 85 20 65]
 [59 90 18 84]
 [74 28 32 60]
 [71 24 88 22]
 [82 42 92 97]
 [62 11 29 10]
 [13 52 89 18]
 [61 41 71 47]]


###`Q-16:` Replace odd elements in arrays with -1.

In [23]:
#Code here
arr=np.arange(90).reshape(15,6)
arr[arr%2!=0]=0
print(arr)

[[ 0  0  2  0  4  0]
 [ 6  0  8  0 10  0]
 [12  0 14  0 16  0]
 [18  0 20  0 22  0]
 [24  0 26  0 28  0]
 [30  0 32  0 34  0]
 [36  0 38  0 40  0]
 [42  0 44  0 46  0]
 [48  0 50  0 52  0]
 [54  0 56  0 58  0]
 [60  0 62  0 64  0]
 [66  0 68  0 70  0]
 [72  0 74  0 76  0]
 [78  0 80  0 82  0]
 [84  0 86  0 88  0]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
res=np.maximum(a,b)
print("Result->",res)

Result-> [6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [34]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
normal=(arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))
print(normal)

[[0.95039683 0.6182122  0.81359649 0.64003759 0.01368003]
 [0.46021303 0.8539056  0.68995405 0.2612782  0.0372807 ]
 [0.25699666 0.20749791 0.57111529 0.7729741  0.95352966]
 [0.15758145 0.67606516 1.         0.50313283 0.05054302]
 [0.15340434 0.73799081 0.99279449 0.42345447 0.90611947]
 [0.         0.11455723 0.55607769 0.51315789 0.78226817]
 [0.35307018 0.81359649 0.30524227 0.09659566 0.22368421]
 [0.60891813 0.72932331 0.61518379 0.6573726  0.36883876]]


In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [57]:
#Code here
def nth_largest(arr,number):
    if number<=len(arr) and number>0:
        sorte_aar=sorted(arr)[::-1]
        print("{} Largest number is {}".format(number,sorte_aar[number-1]))
    else:
        print("Your are going out of range")
nth_largest(np.array([12,34,40,7,1,0]),1)

1 Largest number is 40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [61]:
#code here
a = np.array([1,2,3])
np.hstack((np.repeat(a,len(a)),np.tile(a,len(a))))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])